# Generated by Django 2.2.3 on 2019-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='관리자 로그인 전용으로만 사용할 예정', max_length=50, verbose_name='아이디')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='닉네임')),
                ('uid', models.CharField(blank=True, max_length=50, null=True, verbose_name='카카오 고유 ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
                'db_table': 'users',
            },
        ),
    ]
