# Generated by Django 2.2.3 on 2019-07-13 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화 여부')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='요청 수락 여부')),
                ('confirm_at', models.DateTimeField(blank=True, null=True, verbose_name='수락일')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('friend_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_1', to=settings.AUTH_USER_MODEL, verbose_name='친구 요청을 보낸 사람')),
                ('friend_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_2', to=settings.AUTH_USER_MODEL, verbose_name='친구 요청을 받는 사람')),
            ],
            options={
                'verbose_name': '친구',
                'verbose_name_plural': '친구들',
                'db_table': 'friends',
            },
        ),
    ]
