# Generated by Django 2.2.3 on 2019-07-13 06:58

import apps.letter.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.letter.models.letter_image_path, verbose_name='이미지')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_receiver', to=settings.AUTH_USER_MODEL, verbose_name='받는 사람')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_sender', to=settings.AUTH_USER_MODEL, verbose_name='보낸 사람')),
            ],
            options={
                'verbose_name': '엽서',
                'verbose_name_plural': '엽서들',
                'db_table': 'letters',
            },
        ),
    ]
